### ISSUE TITLE
Give suggestion for how to continue when demo such as Ctrl + W

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/objects#3]

**Comment by gjwgit** [comment]
Perhaps not mention Ctrl-W. The user can figure that out or mouse click to close the graphic window. Good to have "Press Enter to continue" as appropriate in the scripts.

**Comment by simonzhaoms** [comment]
Fixed in commit https://github.com/mlhubber/objects/commit/14ff9c541b7f0532f585e4ef90051b240656a84c
