### ISSUE TITLE
CONFIGURE: Fails due to timeout

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/objects#6]
The connection to http://data.dmlc.ml/mxnet/models/imagenet/synset.txt, the second dependency, does not respond.

This could be a more general issue for MLHub:
1. Need to timeout a query.
2. Need to display what is happening before the connection is attempted as in this case it looks like it is stuck with the previous file.
3. How to deal with links that disappear - perhaps a mlhub cache of such files where license allows it?

**Comment by simonzhaoms** [comment]
The files are uploaded into the repo in 27c5d6c 
1 and 2 should be handled by mlhub, I think.

**Comment by simonzhaoms** [comment]
Related to mlhubber/mlhub#93
